title: nicwn's homepage
description: "Hello there! My name's Nick. I'm a full time dad who likes to tinker with interesting tech. I started my career as a systems analyst at Microsoft in Redmond, then became a data analyst at Yahoo! in NYC, then I led the creation of LEGO CUUSOO in Tokyo! Since then I've mainly been a dad, although I did help launched a few businesses and a NGO, and be a product manager part time. Now I'm living in Germany, tinkering with data and web3."
author: Nicholas Wang
twitter_username: nicwn
github_username: nicwn
linkedin_username: nickwang

# Minima theme configuration
theme: minima
show_excerpts: true
